name: HACS Validation

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
